export const provinces = [
  {
    id: 28,
    value: "A Coruña",
    order: 1,
    key: "a-coruna",
    parent: 17,
  },
  {
    id: 312,
    value: "Aargau",
    order: 1,
    key: "aargau",
    parent: 44,
  },
  {
    id: 80,
    value: "Acre",
    order: 1,
    key: "acre",
    parent: 7,
  },
  {
    id: 734,
    value: "Afganistán",
    order: 1,
    key: "afganistan",
    parent: 86,
  },
  {
    id: 174,
    value: "Aguascalientes",
    order: 1,
    key: "aguascalientes",
    parent: 29,
  },
  {
    id: 108,
    value: "Alabama",
    order: 1,
    key: "alabama",
    parent: 18,
  },
  {
    id: 289,
    value: "Alsace",
    order: 1,
    key: "alsace",
    parent: 20,
  },
  {
    id: 402,
    value: "Andorra la Vella",
    order: 1,
    key: "andorra-la-vella",
    parent: 2,
  },
  {
    id: 735,
    value: "Antigua y Barbuda",
    order: 1,
    key: "antigua-y-barbuda",
    parent: 87,
  },
  {
    id: 160,
    value: "Antofagasta",
    order: 1,
    key: "antofagasta",
    parent: 10,
  },
  {
    id: 232,
    value: "Anzoátegui",
    order: 1,
    key: "anzoategui",
    parent: 46,
  },
  {
    id: 736,
    value: "Arabia Saudita",
    order: 1,
    key: "arabia-saudita",
    parent: 88,
  },
  {
    id: 737,
    value: "Argelia",
    order: 1,
    key: "argelia",
    parent: 89,
  },
  {
    id: 209,
    value: "Armenia",
    order: 1,
    key: "colombia-armenia",
    parent: 11,
  },
  {
    id: 738,
    value: "Armenia",
    order: 1,
    key: "armenia-armenia",
    parent: 90,
  },
  {
    id: 430,
    value: "Aust Agder",
    order: 1,
    key: "aust-agder",
    parent: 31,
  },
  {
    id: 553,
    value: "Australia",
    order: 1,
    key: "australia",
    parent: 59,
  },
  {
    id: 739,
    value: "Azerbaiyán",
    order: 1,
    key: "azerbaiyan",
    parent: 91,
  },
  {
    id: 711,
    value: "Açores",
    order: 1,
    key: "acores",
    parent: 37,
  },
  {
    id: 257,
    value: "Baden - W??rttemberg",
    order: 1,
    key: "baden-wurttemberg",
    parent: 1,
  },
  {
    id: 740,
    value: "Bahamas",
    order: 1,
    key: "bahamas",
    parent: 92,
  },
  {
    id: 55,
    value: "Bahía Blanca",
    order: 1,
    key: "bahia-blanca",
    parent: 3,
  },
  {
    id: 742,
    value: "Bangladés",
    order: 1,
    key: "banglades",
    parent: 94,
  },
  {
    id: 743,
    value: "Barbados",
    order: 1,
    key: "barbados",
    parent: 95,
  },
  {
    id: 741,
    value: "Baréin",
    order: 1,
    key: "barein",
    parent: 93,
  },
  {
    id: 744,
    value: "Belice",
    order: 1,
    key: "belice",
    parent: 96,
  },
  {
    id: 745,
    value: "Benín",
    order: 1,
    key: "benin",
    parent: 97,
  },
  {
    id: 861,
    value: "Bermuda",
    order: 1,
    key: "Bermuda",
    parent: 210,
  },
  {
    id: 746,
    value: "Birmania",
    order: 1,
    key: "birmania",
    parent: 98,
  },
  {
    id: 408,
    value: "Blekinge l??n",
    order: 1,
    key: "blekinge-lan",
    parent: 43,
  },
  {
    id: 525,
    value: "Bolivia",
    order: 1,
    key: "bolivia",
    parent: 6,
  },
  {
    id: 385,
    value: "Bornholms Amt",
    order: 1,
    key: "bornholms-amt",
    parent: 14,
  },
  {
    id: 747,
    value: "Botsuana",
    order: 1,
    key: "botsuana",
    parent: 99,
  },
  {
    id: 748,
    value: "Brunéi",
    order: 1,
    key: "brunei",
    parent: 100,
  },
  {
    id: 526,
    value: "Bulgaria",
    order: 1,
    key: "bulgaria",
    parent: 8,
  },
  {
    id: 354,
    value: "Burgenland",
    order: 1,
    key: "burgenland",
    parent: 4,
  },
  {
    id: 749,
    value: "Burkina Faso",
    order: 1,
    key: "burkina-faso",
    parent: 101,
  },
  {
    id: 750,
    value: "Burundi",
    order: 1,
    key: "burundi",
    parent: 102,
  },
  {
    id: 751,
    value: "Bután",
    order: 1,
    key: "butan",
    parent: 103,
  },
  {
    id: 524,
    value: "Bélgica",
    order: 1,
    key: "belgica",
    parent: 5,
  },
  {
    id: 752,
    value: "Cabo Verde",
    order: 1,
    key: "cabo-verde",
    parent: 104,
  },
  {
    id: 753,
    value: "Camboya",
    order: 1,
    key: "camboya",
    parent: 105,
  },
  {
    id: 754,
    value: "Camerún",
    order: 1,
    key: "camerun",
    parent: 106,
  },
  {
    id: 556,
    value: "Canadá",
    order: 1,
    key: "canada",
    parent: 63,
  },
  {
    id: 819,
    value: "Catar",
    order: 1,
    key: "catar",
    parent: 171,
  },
  {
    id: 756,
    value: "Chad",
    order: 1,
    key: "chad",
    parent: 108,
  },
  {
    id: 339,
    value: "Channel Islands",
    order: 1,
    key: "channel-islands",
    parent: 39,
  },
  {
    id: 527,
    value: "Chequia",
    order: 1,
    key: "chequia",
    parent: 9,
  },
  {
    id: 550,
    value: "China",
    order: 1,
    key: "china",
    parent: 55,
  },
  {
    id: 757,
    value: "Comoras",
    order: 1,
    key: "comoras",
    parent: 109,
  },
  {
    id: 760,
    value: "Corea del Norte",
    order: 1,
    key: "corea-del-norte",
    parent: 112,
  },
  {
    id: 761,
    value: "Corea del Sur",
    order: 1,
    key: "corea-del-sur",
    parent: 113,
  },
  {
    id: 450,
    value: "Cork",
    order: 1,
    key: "cork",
    parent: 49,
  },
  {
    id: 528,
    value: "Costa Rica",
    order: 1,
    key: "costa-rica",
    parent: 12,
  },
  {
    id: 762,
    value: "Costa de Marfil",
    order: 1,
    key: "costa-de-marfil",
    parent: 114,
  },
  {
    id: 529,
    value: "Cuba",
    order: 1,
    key: "cuba",
    parent: 13,
  },
  {
    id: 763,
    value: "Dominica",
    order: 1,
    key: "dominica",
    parent: 115,
  },
  {
    id: 466,
    value: "Drenthe",
    order: 1,
    key: "drenthe",
    parent: 23,
  },
  {
    id: 530,
    value: "Ecuador",
    order: 1,
    key: "ecuador",
    parent: 15,
  },
  {
    id: 764,
    value: "Egipto",
    order: 1,
    key: "egipto",
    parent: 116,
  },
  {
    id: 531,
    value: "El Salvador",
    order: 1,
    key: "el-salvador",
    parent: 16,
  },
  {
    id: 765,
    value: "Emiratos Árabes Unidos",
    order: 1,
    key: "emiratos-arabes-unidos",
    parent: 117,
  },
  {
    id: 766,
    value: "Eritrea",
    order: 1,
    key: "eritrea",
    parent: 118,
  },
  {
    id: 767,
    value: "Etiopía",
    order: 1,
    key: "etiopia",
    parent: 119,
  },
  {
    id: 768,
    value: "Filipinas",
    order: 1,
    key: "filipinas",
    parent: 120,
  },
  {
    id: 769,
    value: "Fiyi",
    order: 1,
    key: "fiyi",
    parent: 121,
  },
  {
    id: 770,
    value: "Gabón",
    order: 1,
    key: "gabon",
    parent: 122,
  },
  {
    id: 771,
    value: "Gambia",
    order: 1,
    key: "gambia",
    parent: 123,
  },
  {
    id: 772,
    value: "Georgia",
    order: 1,
    key: "georgia-georgia",
    parent: 124,
  },
  {
    id: 773,
    value: "Ghana",
    order: 1,
    key: "ghana",
    parent: 125,
  },
  {
    id: 774,
    value: "Granada",
    order: 1,
    key: "granada-granada",
    parent: 126,
  },
  {
    id: 532,
    value: "Guatemala",
    order: 1,
    key: "guatemala",
    parent: 22,
  },
  {
    id: 775,
    value: "Guinea",
    order: 1,
    key: "guinea",
    parent: 127,
  },
  {
    id: 776,
    value: "Guinea Ecuatorial",
    order: 1,
    key: "guinea-ecuatorial",
    parent: 128,
  },
  {
    id: 777,
    value: "Guinea-Bissau",
    order: 1,
    key: "guinea-bissau",
    parent: 129,
  },
  {
    id: 778,
    value: "Guyana",
    order: 1,
    key: "guyana",
    parent: 130,
  },
  {
    id: 779,
    value: "Haití",
    order: 1,
    key: "haiti",
    parent: 131,
  },
  {
    id: 780,
    value: "Honduras",
    order: 1,
    key: "honduras",
    parent: 132,
  },
  {
    id: 533,
    value: "Hungría",
    order: 1,
    key: "hungria",
    parent: 24,
  },
  {
    id: 551,
    value: "India",
    order: 1,
    key: "india",
    parent: 56,
  },
  {
    id: 781,
    value: "Indonesia",
    order: 1,
    key: "indonesia",
    parent: 133,
  },
  {
    id: 783,
    value: "Irak",
    order: 1,
    key: "irak",
    parent: 135,
  },
  {
    id: 782,
    value: "Irán",
    order: 1,
    key: "iran",
    parent: 134,
  },
  {
    id: 534,
    value: "Islandia",
    order: 1,
    key: "islandia",
    parent: 25,
  },
  {
    id: 455,
    value: "Islas Aegea",
    order: 1,
    key: "islas-aegea",
    parent: 21,
  },
  {
    id: 803,
    value: "Islas Marshall",
    order: 1,
    key: "islas-marshall",
    parent: 155,
  },
  {
    id: 821,
    value: "Islas Salomón",
    order: 1,
    key: "islas-salomon",
    parent: 173,
  },
  {
    id: 784,
    value: "Israel",
    order: 1,
    key: "israel",
    parent: 136,
  },
  {
    id: 785,
    value: "Jamaica",
    order: 1,
    key: "jamaica",
    parent: 137,
  },
  {
    id: 535,
    value: "Japón",
    order: 1,
    key: "japon",
    parent: 27,
  },
  {
    id: 786,
    value: "Jordania",
    order: 1,
    key: "jordania",
    parent: 138,
  },
  {
    id: 787,
    value: "Kazajistán",
    order: 1,
    key: "kazajistan",
    parent: 139,
  },
  {
    id: 788,
    value: "Kenia",
    order: 1,
    key: "kenia",
    parent: 140,
  },
  {
    id: 789,
    value: "Kirguistán",
    order: 1,
    key: "kirguistan",
    parent: 141,
  },
  {
    id: 790,
    value: "Kiribati",
    order: 1,
    key: "kiribati",
    parent: 142,
  },
  {
    id: 791,
    value: "Kuwait",
    order: 1,
    key: "kuwait",
    parent: 143,
  },
  {
    id: 792,
    value: "Laos",
    order: 1,
    key: "laos",
    parent: 144,
  },
  {
    id: 793,
    value: "Lesoto",
    order: 1,
    key: "lesoto",
    parent: 145,
  },
  {
    id: 795,
    value: "Liberia",
    order: 1,
    key: "liberia",
    parent: 147,
  },
  {
    id: 796,
    value: "Libia",
    order: 1,
    key: "libia",
    parent: 148,
  },
  {
    id: 255,
    value: "Liechtenstein",
    order: 1,
    key: "liechtenstein",
    parent: 50,
  },
  {
    id: 536,
    value: "Luxemburgo",
    order: 1,
    key: "luxemburgo",
    parent: 28,
  },
  {
    id: 794,
    value: "Líbano",
    order: 1,
    key: "libano",
    parent: 146,
  },
  {
    id: 797,
    value: "Madagascar",
    order: 1,
    key: "madagascar",
    parent: 149,
  },
  {
    id: 798,
    value: "Malasia",
    order: 1,
    key: "malasia",
    parent: 150,
  },
  {
    id: 799,
    value: "Malaui",
    order: 1,
    key: "malaui",
    parent: 151,
  },
  {
    id: 800,
    value: "Maldivas",
    order: 1,
    key: "maldivas",
    parent: 152,
  },
  {
    id: 801,
    value: "Malí",
    order: 1,
    key: "mali",
    parent: 153,
  },
  {
    id: 802,
    value: "Marruecos",
    order: 1,
    key: "marruecos",
    parent: 154,
  },
  {
    id: 804,
    value: "Mauricio",
    order: 1,
    key: "mauricio",
    parent: 156,
  },
  {
    id: 805,
    value: "Mauritania",
    order: 1,
    key: "mauritania",
    parent: 157,
  },
  {
    id: 806,
    value: "Micronesia",
    order: 1,
    key: "micronesia",
    parent: 158,
  },
  {
    id: 807,
    value: "Mongolia",
    order: 1,
    key: "mongolia",
    parent: 159,
  },
  {
    id: 808,
    value: "Montenegro",
    order: 1,
    key: "montenegro",
    parent: 160,
  },
  {
    id: 809,
    value: "Mozambique",
    order: 1,
    key: "mozambique",
    parent: 161,
  },
  {
    id: 810,
    value: "Namibia",
    order: 1,
    key: "namibia",
    parent: 162,
  },
  {
    id: 811,
    value: "Nauru",
    order: 1,
    key: "nauru",
    parent: 163,
  },
  {
    id: 812,
    value: "Nepal",
    order: 1,
    key: "nepal",
    parent: 164,
  },
  {
    id: 537,
    value: "Nicaragua",
    order: 1,
    key: "nicaragua",
    parent: 30,
  },
  {
    id: 814,
    value: "Nigeria",
    order: 1,
    key: "nigeria",
    parent: 166,
  },
  {
    id: 554,
    value: "Nueva Zelanda",
    order: 1,
    key: "nueva-zelanda",
    parent: 60,
  },
  {
    id: 813,
    value: "Níger",
    order: 1,
    key: "niger",
    parent: 165,
  },
  {
    id: 815,
    value: "Omán",
    order: 1,
    key: "oman",
    parent: 167,
  },
  {
    id: 1,
    value: "Otro País",
    order: 1,
    key: "otro-pais",
    parent: 32,
  },
  {
    id: 816,
    value: "Pakistán",
    order: 1,
    key: "pakistan",
    parent: 168,
  },
  {
    id: 817,
    value: "Palaos",
    order: 1,
    key: "palaos",
    parent: 169,
  },
  {
    id: 538,
    value: "Panamá",
    order: 1,
    key: "panama",
    parent: 33,
  },
  {
    id: 818,
    value: "Papúa Nueva Guinea",
    order: 1,
    key: "papua-nueva-guinea",
    parent: 170,
  },
  {
    id: 539,
    value: "Paraguay",
    order: 1,
    key: "paraguay",
    parent: 34,
  },
  {
    id: 540,
    value: "Perú",
    order: 1,
    key: "peru",
    parent: 35,
  },
  {
    id: 541,
    value: "Polonia",
    order: 1,
    key: "polonia",
    parent: 36,
  },
  {
    id: 542,
    value: "Puerto Rico",
    order: 1,
    key: "puerto-rico",
    parent: 38,
  },
  {
    id: 759,
    value: "Rep. Dem. del Congo",
    order: 1,
    key: "rep.-dem.-del-congo",
    parent: 111,
  },
  {
    id: 543,
    value: "Rep. Dominicana",
    order: 1,
    key: "rep.-dominicana",
    parent: 40,
  },
  {
    id: 755,
    value: "República Centroafricana",
    order: 1,
    key: "republica-centroafricana",
    parent: 107,
  },
  {
    id: 758,
    value: "República del Congo",
    order: 1,
    key: "republica-del-congo",
    parent: 110,
  },
  {
    id: 552,
    value: "Resto de Asia",
    order: 1,
    key: "resto-de-asia",
    parent: 57,
  },
  {
    id: 548,
    value: "Resto de Europa",
    order: 1,
    key: "resto-de-europa",
    parent: 51,
  },
  {
    id: 549,
    value: "Resto de Lat.",
    order: 1,
    key: "resto-de-lat.",
    parent: 53,
  },
  {
    id: 555,
    value: "Resto de Oceania",
    order: 1,
    key: "resto-de-oceania",
    parent: 61,
  },
  {
    id: 820,
    value: "Ruanda",
    order: 1,
    key: "ruanda",
    parent: 172,
  },
  {
    id: 544,
    value: "Rumania",
    order: 1,
    key: "rumania",
    parent: 41,
  },
  {
    id: 545,
    value: "Rusia",
    order: 1,
    key: "rusia",
    parent: 42,
  },
  {
    id: 822,
    value: "Samoa",
    order: 1,
    key: "samoa",
    parent: 174,
  },
  {
    id: 823,
    value: "San Cristóbal y Nieves",
    order: 1,
    key: "san-cristobal-y-nieves",
    parent: 175,
  },
  {
    id: 824,
    value: "San Vicente y las Granadinas",
    order: 1,
    key: "san-vicente-y-las-granadinas",
    parent: 176,
  },
  {
    id: 825,
    value: "Santa Lucía",
    order: 1,
    key: "santa-lucia",
    parent: 177,
  },
  {
    id: 826,
    value: "Santo Tomé y Príncipe",
    order: 1,
    key: "santo-tome-y-principe",
    parent: 178,
  },
  {
    id: 827,
    value: "Senegal",
    order: 1,
    key: "senegal",
    parent: 179,
  },
  {
    id: 547,
    value: "Serbia y Montenegro",
    order: 1,
    key: "serbia-y-montenegro",
    parent: 47,
  },
  {
    id: 828,
    value: "Seychelles",
    order: 1,
    key: "seychelles",
    parent: 180,
  },
  {
    id: 829,
    value: "Sierra Leona",
    order: 1,
    key: "sierra-leona",
    parent: 181,
  },
  {
    id: 830,
    value: "Singapur",
    order: 1,
    key: "singapur",
    parent: 182,
  },
  {
    id: 831,
    value: "Siria",
    order: 1,
    key: "siria",
    parent: 183,
  },
  {
    id: 832,
    value: "Somalia",
    order: 1,
    key: "somalia",
    parent: 184,
  },
  {
    id: 833,
    value: "Sri Lanka",
    order: 1,
    key: "sri-lanka",
    parent: 185,
  },
  {
    id: 834,
    value: "Suazilandia",
    order: 1,
    key: "suazilandia",
    parent: 186,
  },
  {
    id: 835,
    value: "Sudáfrica",
    order: 1,
    key: "sudafrica",
    parent: 187,
  },
  {
    id: 836,
    value: "Sudán",
    order: 1,
    key: "sudan",
    parent: 188,
  },
  {
    id: 837,
    value: "Sudán del Sur",
    order: 1,
    key: "sudan-del-sur",
    parent: 189,
  },
  {
    id: 838,
    value: "Surinam",
    order: 1,
    key: "surinam",
    parent: 190,
  },
  {
    id: 839,
    value: "Tailandia",
    order: 1,
    key: "tailandia",
    parent: 191,
  },
  {
    id: 857,
    value: "Taiwán",
    order: 1,
    key: "taiwan",
    parent: 209,
  },
  {
    id: 840,
    value: "Tanzania",
    order: 1,
    key: "tanzania",
    parent: 192,
  },
  {
    id: 841,
    value: "Tayikistán",
    order: 1,
    key: "tayikistan",
    parent: 193,
  },
  {
    id: 842,
    value: "Timor Oriental",
    order: 1,
    key: "timor-oriental",
    parent: 194,
  },
  {
    id: 843,
    value: "Togo",
    order: 1,
    key: "togo",
    parent: 195,
  },
  {
    id: 844,
    value: "Tonga",
    order: 1,
    key: "tonga",
    parent: 196,
  },
  {
    id: 845,
    value: "Trinidad y Tobago",
    order: 1,
    key: "trinidad-y-tobago",
    parent: 197,
  },
  {
    id: 847,
    value: "Turkmenistán",
    order: 1,
    key: "turkmenistan",
    parent: 199,
  },
  {
    id: 848,
    value: "Tuvalu",
    order: 1,
    key: "tuvalu",
    parent: 200,
  },
  {
    id: 846,
    value: "Túnez",
    order: 1,
    key: "tunez",
    parent: 198,
  },
  {
    id: 849,
    value: "Uganda",
    order: 1,
    key: "uganda",
    parent: 201,
  },
  {
    id: 546,
    value: "Uruguay",
    order: 1,
    key: "uruguay",
    parent: 45,
  },
  {
    id: 850,
    value: "Uzbekistán",
    order: 1,
    key: "uzbekistan",
    parent: 202,
  },
  {
    id: 851,
    value: "Vanuatu",
    order: 1,
    key: "vanuatu",
    parent: 203,
  },
  {
    id: 852,
    value: "Vietnam",
    order: 1,
    key: "vietnam",
    parent: 204,
  },
  {
    id: 853,
    value: "Yemen",
    order: 1,
    key: "yemen",
    parent: 205,
  },
  {
    id: 854,
    value: "Yibuti",
    order: 1,
    key: "yibuti",
    parent: 206,
  },
  {
    id: 855,
    value: "Zambia",
    order: 1,
    key: "zambia",
    parent: 207,
  },
  {
    id: 856,
    value: "Zimbabue",
    order: 1,
    key: "zimbabue",
    parent: 208,
  },
  {
    id: 601,
    value: "[Abruzos] Chieti",
    order: 1,
    key: "abruzos-chieti",
    parent: 26,
  },
  {
    id: 479,
    value: "Åland",
    order: 1,
    key: "land",
    parent: 19,
  },
  {
    id: 81,
    value: "Alagoas",
    order: 2,
    key: "alagoas",
    parent: 7,
  },
  {
    id: 109,
    value: "Alaska",
    order: 2,
    key: "alaska",
    parent: 18,
  },
  {
    id: 859,
    value: "Antilles françaises",
    order: 2,
    key: "antilles-francaises",
    parent: 20,
  },
  {
    id: 314,
    value: "Appenzell Auserrodhen",
    order: 2,
    key: "appenzell-auserrodhen",
    parent: 44,
  },
  {
    id: 233,
    value: "Apure",
    order: 2,
    key: "apure",
    parent: 46,
  },
  {
    id: 161,
    value: "Atacama",
    order: 2,
    key: "atacama",
    parent: 10,
  },
  {
    id: 712,
    value: "Aveiro",
    order: 2,
    key: "aveiro",
    parent: 37,
  },
  {
    id: 175,
    value: "Baja California",
    order: 2,
    key: "baja-california",
    parent: 29,
  },
  {
    id: 210,
    value: "Barranquilla",
    order: 2,
    key: "barranquilla",
    parent: 11,
  },
  {
    id: 258,
    value: "Bayern",
    order: 2,
    key: "bayern",
    parent: 1,
  },
  {
    id: 56,
    value: "Buenos Aires",
    order: 2,
    key: "buenos-aires",
    parent: 3,
  },
  {
    id: 431,
    value: "Buskerud",
    order: 2,
    key: "buskerud",
    parent: 31,
  },
  {
    id: 407,
    value: "Canillo",
    order: 2,
    key: "canillo",
    parent: 2,
  },
  {
    id: 409,
    value: "Dalarnas l??n",
    order: 2,
    key: "dalarnas-lan",
    parent: 43,
  },
  {
    id: 449,
    value: "Dublin",
    order: 2,
    key: "dublin",
    parent: 49,
  },
  {
    id: 340,
    value: "East Anglia",
    order: 2,
    key: "east-anglia",
    parent: 39,
  },
  {
    id: 480,
    value: "Finlandia del Este",
    order: 2,
    key: "finlandia-del-este",
    parent: 19,
  },
  {
    id: 467,
    value: "Flevoland",
    order: 2,
    key: "flevoland",
    parent: 23,
  },
  {
    id: 386,
    value: "F??r??erne",
    order: 2,
    key: "f-r-erne",
    parent: 14,
  },
  {
    id: 456,
    value: "Grecia Central y Evvoia",
    order: 2,
    key: "grecia-central-y-evvoia",
    parent: 21,
  },
  {
    id: 355,
    value: "K??rnten",
    order: 2,
    key: "karnten",
    parent: 4,
  },
  {
    id: 602,
    value: "[Abruzos] L'Aquila",
    order: 2,
    key: "abruzos-l-aquila",
    parent: 26,
  },
  {
    id: 2,
    value: "Álava/Araba",
    order: 2,
    key: "alava-araba",
    parent: 17,
  },
  {
    id: 3,
    value: "Albacete",
    order: 3,
    key: "albacete",
    parent: 17,
  },
  {
    id: 82,
    value: "Amapá",
    order: 3,
    key: "amapa",
    parent: 7,
  },
  {
    id: 313,
    value: "Appenzell Innerrodhen",
    order: 3,
    key: "appenzell-innerrodhen",
    parent: 44,
  },
  {
    id: 290,
    value: "Aquitaine",
    order: 3,
    key: "aquitaine",
    parent: 20,
  },
  {
    id: 234,
    value: "Aragua",
    order: 3,
    key: "aragua",
    parent: 46,
  },
  {
    id: 110,
    value: "Arizona",
    order: 3,
    key: "arizona",
    parent: 18,
  },
  {
    id: 176,
    value: "Baja California Sur",
    order: 3,
    key: "baja-california-sur",
    parent: 29,
  },
  {
    id: 713,
    value: "Beja",
    order: 3,
    key: "beja",
    parent: 37,
  },
  {
    id: 259,
    value: "Berlin",
    order: 3,
    key: "berlin",
    parent: 1,
  },
  {
    id: 211,
    value: "Bogotá",
    order: 3,
    key: "bogota",
    parent: 11,
  },
  {
    id: 162,
    value: "Bío Bío",
    order: 3,
    key: "bio-bio",
    parent: 10,
  },
  {
    id: 57,
    value: "Capital Federal",
    order: 3,
    key: "capital-federal",
    parent: 3,
  },
  {
    id: 457,
    value: "Creta",
    order: 3,
    key: "creta",
    parent: 21,
  },
  {
    id: 341,
    value: "East Midlands",
    order: 3,
    key: "east-midlands",
    parent: 39,
  },
  {
    id: 401,
    value: "Encamp",
    order: 3,
    key: "encamp",
    parent: 2,
  },
  {
    id: 481,
    value: "Finlandia del Oeste",
    order: 3,
    key: "finlandia-del-oeste",
    parent: 19,
  },
  {
    id: 432,
    value: "Finnmark",
    order: 3,
    key: "finnmark",
    parent: 31,
  },
  {
    id: 387,
    value: "Frederiksborg Amt",
    order: 3,
    key: "frederiksborg-amt",
    parent: 14,
  },
  {
    id: 468,
    value: "Friesland",
    order: 3,
    key: "friesland",
    parent: 23,
  },
  {
    id: 451,
    value: "Galway",
    order: 3,
    key: "galway",
    parent: 49,
  },
  {
    id: 410,
    value: "Gotlands l??n",
    order: 3,
    key: "gotlands-lan",
    parent: 43,
  },
  {
    id: 356,
    value: "Niederösterreich",
    order: 3,
    key: "niederosterreich",
    parent: 4,
  },
  {
    id: 603,
    value: "[Abruzos] Pescara",
    order: 3,
    key: "abruzos-pescara",
    parent: 26,
  },
  {
    id: 4,
    value: "Alicante/Alacant",
    order: 4,
    key: "alicante-alacant",
    parent: 17,
  },
  {
    id: 83,
    value: "Amazonas",
    order: 4,
    key: "amazonas",
    parent: 7,
  },
  {
    id: 111,
    value: "Arkansas",
    order: 4,
    key: "arkansas",
    parent: 18,
  },
  {
    id: 291,
    value: "Auvergne",
    order: 4,
    key: "auvergne",
    parent: 20,
  },
  {
    id: 235,
    value: "Barinas",
    order: 4,
    key: "barinas",
    parent: 46,
  },
  {
    id: 316,
    value: "Basel Land",
    order: 4,
    key: "basel-land",
    parent: 44,
  },
  {
    id: 714,
    value: "Braga",
    order: 4,
    key: "braga",
    parent: 37,
  },
  {
    id: 260,
    value: "Brandenburg",
    order: 4,
    key: "brandenburg",
    parent: 1,
  },
  {
    id: 212,
    value: "Bucaramanga",
    order: 4,
    key: "bucaramanga",
    parent: 11,
  },
  {
    id: 177,
    value: "Campeche",
    order: 4,
    key: "campeche",
    parent: 29,
  },
  {
    id: 58,
    value: "Catamarca",
    order: 4,
    key: "catamarca",
    parent: 3,
  },
  {
    id: 163,
    value: "Coquimbo",
    order: 4,
    key: "coquimbo",
    parent: 10,
  },
  {
    id: 458,
    value: "Epirus",
    order: 4,
    key: "epirus",
    parent: 21,
  },
  {
    id: 482,
    value: "Finlandia del Sur - Helsinki",
    order: 4,
    key: "finlandia-del-sur-helsinki",
    parent: 19,
  },
  {
    id: 388,
    value: "Fyns Amt",
    order: 4,
    key: "fyns-amt",
    parent: 14,
  },
  {
    id: 469,
    value: "Gelderland",
    order: 4,
    key: "gelderland",
    parent: 23,
  },
  {
    id: 858,
    value: "Gibraltar",
    order: 4,
    key: "gibraltar",
    parent: 39,
  },
  {
    id: 411,
    value: "G??vleborgs l??n",
    order: 4,
    key: "gavleborgs-lan",
    parent: 43,
  },
  {
    id: 433,
    value: "Hedmark",
    order: 4,
    key: "hedmark",
    parent: 31,
  },
  {
    id: 860,
    value: "Kerry",
    order: 4,
    key: "kerry",
    parent: 49,
  },
  {
    id: 403,
    value: "La Massana",
    order: 4,
    key: "la-massana",
    parent: 2,
  },
  {
    id: 357,
    value: "Oberösterreich",
    order: 4,
    key: "oberosterreich",
    parent: 4,
  },
  {
    id: 604,
    value: "[Abruzos] Teramo",
    order: 4,
    key: "abruzos-teramo",
    parent: 26,
  },
  {
    id: 5,
    value: "Almería",
    order: 5,
    key: "almeria",
    parent: 17,
  },
  {
    id: 84,
    value: "Bahia",
    order: 5,
    key: "bahia",
    parent: 7,
  },
  {
    id: 317,
    value: "Basel Stadt",
    order: 5,
    key: "basel-stadt",
    parent: 44,
  },
  {
    id: 292,
    value: "Basse Normandie",
    order: 5,
    key: "basse-normandie",
    parent: 20,
  },
  {
    id: 236,
    value: "Bolívar",
    order: 5,
    key: "bolivar",
    parent: 46,
  },
  {
    id: 715,
    value: "Bragança",
    order: 5,
    key: "braganca",
    parent: 37,
  },
  {
    id: 261,
    value: "Bremen",
    order: 5,
    key: "bremen",
    parent: 1,
  },
  {
    id: 213,
    value: "Buga",
    order: 5,
    key: "buga",
    parent: 11,
  },
  {
    id: 112,
    value: "California",
    order: 5,
    key: "california",
    parent: 18,
  },
  {
    id: 59,
    value: "Chaco",
    order: 5,
    key: "chaco",
    parent: 3,
  },
  {
    id: 178,
    value: "Chiapas",
    order: 5,
    key: "chiapas",
    parent: 29,
  },
  {
    id: 470,
    value: "Groningen",
    order: 5,
    key: "groningen",
    parent: 23,
  },
  {
    id: 389,
    value: "Gr??nland",
    order: 5,
    key: "gr-nland",
    parent: 14,
  },
  {
    id: 412,
    value: "Hallands l??n",
    order: 5,
    key: "hallands-lan",
    parent: 43,
  },
  {
    id: 342,
    value: "Home Counties",
    order: 5,
    key: "home-counties",
    parent: 39,
  },
  {
    id: 434,
    value: "Hordaland m/Bergen",
    order: 5,
    key: "hordaland-m-bergen",
    parent: 31,
  },
  {
    id: 164,
    value: "Isla de Pascua",
    order: 5,
    key: "isla-de-pascua",
    parent: 10,
  },
  {
    id: 459,
    value: "Islas Ionian (Eptanese)",
    order: 5,
    key: "islas-ionian-eptanese",
    parent: 21,
  },
  {
    id: 483,
    value: "Lapland",
    order: 5,
    key: "lapland",
    parent: 19,
  },
  {
    id: 404,
    value: "Les Escaldes - Engordany",
    order: 5,
    key: "les-escaldes-engordany",
    parent: 2,
  },
  {
    id: 452,
    value: "Limerick",
    order: 5,
    key: "limerick",
    parent: 49,
  },
  {
    id: 358,
    value: "Salzburg",
    order: 5,
    key: "salzburg",
    parent: 4,
  },
  {
    id: 605,
    value: "[Basilicata] Matera",
    order: 5,
    key: "basilicata-matera",
    parent: 26,
  },
  {
    id: 6,
    value: "Asturias",
    order: 6,
    key: "asturias",
    parent: 17,
  },
  {
    id: 315,
    value: "Bern",
    order: 6,
    key: "bern",
    parent: 44,
  },
  {
    id: 293,
    value: "Bourgogne",
    order: 6,
    key: "bourgogne",
    parent: 20,
  },
  {
    id: 214,
    value: "Cali",
    order: 6,
    key: "cali",
    parent: 11,
  },
  {
    id: 237,
    value: "Carabobo",
    order: 6,
    key: "carabobo",
    parent: 46,
  },
  {
    id: 716,
    value: "Castelo Branco",
    order: 6,
    key: "castelo-branco",
    parent: 37,
  },
  {
    id: 85,
    value: "Ceará",
    order: 6,
    key: "ceara",
    parent: 7,
  },
  {
    id: 179,
    value: "Chihuahua",
    order: 6,
    key: "chihuahua",
    parent: 29,
  },
  {
    id: 60,
    value: "Chubut",
    order: 6,
    key: "chubut",
    parent: 3,
  },
  {
    id: 113,
    value: "Colorado",
    order: 6,
    key: "colorado",
    parent: 18,
  },
  {
    id: 262,
    value: "Hamburg",
    order: 6,
    key: "hamburg",
    parent: 1,
  },
  {
    id: 413,
    value: "J??mtlands l??n",
    order: 6,
    key: "jamtlands-lan",
    parent: 43,
  },
  {
    id: 390,
    value: "K??benhams Amt",
    order: 6,
    key: "k-benhams-amt",
    parent: 14,
  },
  {
    id: 165,
    value: "La Araucanma",
    order: 6,
    key: "la-araucanma",
    parent: 10,
  },
  {
    id: 471,
    value: "Limburg",
    order: 6,
    key: "limburg",
    parent: 23,
  },
  {
    id: 343,
    value: "London",
    order: 6,
    key: "london",
    parent: 39,
  },
  {
    id: 460,
    value: "Macedonia",
    order: 6,
    key: "grecia-macedonia",
    parent: 21,
  },
  {
    id: 435,
    value: "M??re og Romsdal",
    order: 6,
    key: "m-re-og-romsdal",
    parent: 31,
  },
  {
    id: 453,
    value: "Northern Ireland",
    order: 6,
    key: "Irlanda-northern-ireland",
    parent: 49,
  },
  {
    id: 405,
    value: "Ordino",
    order: 6,
    key: "ordino",
    parent: 2,
  },
  {
    id: 484,
    value: "Oulu",
    order: 6,
    key: "oulu",
    parent: 19,
  },
  {
    id: 359,
    value: "Steiermark",
    order: 6,
    key: "steiermark",
    parent: 4,
  },
  {
    id: 606,
    value: "[Basilicata] Potenza",
    order: 6,
    key: "basilicata-potenza",
    parent: 26,
  },
  {
    id: 294,
    value: "Bretagne",
    order: 7,
    key: "bretagne",
    parent: 20,
  },
  {
    id: 331,
    value: "Canton Ticino",
    order: 7,
    key: "canton-ticino",
    parent: 44,
  },
  {
    id: 215,
    value: "Cartagena",
    order: 7,
    key: "cartagena",
    parent: 11,
  },
  {
    id: 180,
    value: "Coahuila",
    order: 7,
    key: "coahuila",
    parent: 29,
  },
  {
    id: 717,
    value: "Coimbra",
    order: 7,
    key: "coimbra",
    parent: 37,
  },
  {
    id: 114,
    value: "Connecticut",
    order: 7,
    key: "connecticut",
    parent: 18,
  },
  {
    id: 61,
    value: "Corrientes",
    order: 7,
    key: "corrientes",
    parent: 3,
  },
  {
    id: 238,
    value: "Delta Amacuro",
    order: 7,
    key: "delta-amacuro",
    parent: 46,
  },
  {
    id: 86,
    value: "Distrito Federal",
    order: 7,
    key: "brasil-distrito-federal",
    parent: 7,
  },
  {
    id: 263,
    value: "Hessen",
    order: 7,
    key: "hessen",
    parent: 1,
  },
  {
    id: 414,
    value: "Jönköpings l??n",
    order: 7,
    key: "jonkopings-lan",
    parent: 43,
  },
  {
    id: 166,
    value: "Libertador Gral Bernardo O'Higgins",
    order: 7,
    key: "libertador-gral-bernardo-o-higgins",
    parent: 10,
  },
  {
    id: 461,
    value: "Mt. Athos (Ayion Oros)",
    order: 7,
    key: "mt.-athos-ayion-oros",
    parent: 21,
  },
  {
    id: 472,
    value: "Noord Brabant",
    order: 7,
    key: "noord-brabant",
    parent: 23,
  },
  {
    id: 436,
    value: "Nord - Tr??ndelag",
    order: 7,
    key: "nord-tr-ndelag",
    parent: 31,
  },
  {
    id: 391,
    value: "Nordjyllands Amt",
    order: 7,
    key: "nordjyllands-amt",
    parent: 14,
  },
  {
    id: 344,
    value: "North East",
    order: 7,
    key: "north-east",
    parent: 39,
  },
  {
    id: 406,
    value: "Sant Julià de Lòria",
    order: 7,
    key: "sant-julia-de-loria",
    parent: 2,
  },
  {
    id: 360,
    value: "Tirol",
    order: 7,
    key: "tirol",
    parent: 4,
  },
  {
    id: 607,
    value: "[Calabria] Catanzaro",
    order: 7,
    key: "calabria-catanzaro",
    parent: 26,
  },
  {
    id: 7,
    value: "Ávila",
    order: 7,
    key: "avila",
    parent: 17,
  },
  {
    id: 8,
    value: "Badajoz",
    order: 8,
    key: "badajoz",
    parent: 17,
  },
  {
    id: 295,
    value: "Centre Val de Loire",
    order: 8,
    key: "centre-val-de-loire",
    parent: 20,
  },
  {
    id: 181,
    value: "Colima",
    order: 8,
    key: "colima",
    parent: 29,
  },
  {
    id: 216,
    value: "Cucuta",
    order: 8,
    key: "cucuta",
    parent: 11,
  },
  {
    id: 62,
    value: "Córdoba",
    order: 8,
    key: "argentina-cordoba",
    parent: 3,
  },
  {
    id: 115,
    value: "Delaware",
    order: 8,
    key: "delaware",
    parent: 18,
  },
  {
    id: 239,
    value: "Distrito Federal",
    order: 8,
    key: "venezuela-distrito-federal",
    parent: 46,
  },
  {
    id: 87,
    value: "Espírito Santo",
    order: 8,
    key: "espirito-santo",
    parent: 7,
  },
  {
    id: 318,
    value: "Freiburg",
    order: 8,
    key: "freiburg",
    parent: 44,
  },
  {
    id: 415,
    value: "Kalmar l??n",
    order: 8,
    key: "kalmar-lan",
    parent: 43,
  },
  {
    id: 167,
    value: "Los Lagos",
    order: 8,
    key: "los-lagos",
    parent: 10,
  },
  {
    id: 264,
    value: "Mecklenburg - Vorpommern",
    order: 8,
    key: "mecklenburg-vorpommern",
    parent: 1,
  },
  {
    id: 473,
    value: "Noord Holland",
    order: 8,
    key: "noord-holland",
    parent: 23,
  },
  {
    id: 437,
    value: "Nordland",
    order: 8,
    key: "nordland",
    parent: 31,
  },
  {
    id: 345,
    value: "North West",
    order: 8,
    key: "north-west",
    parent: 39,
  },
  {
    id: 462,
    value: "Peloponeso",
    order: 8,
    key: "peloponeso",
    parent: 21,
  },
  {
    id: 392,
    value: "Ribe Amt",
    order: 8,
    key: "ribe-amt",
    parent: 14,
  },
  {
    id: 361,
    value: "Vorarlberg",
    order: 8,
    key: "vorarlberg",
    parent: 4,
  },
  {
    id: 608,
    value: "[Calabria] Cosenza",
    order: 8,
    key: "calabria-cosenza",
    parent: 26,
  },
  {
    id: 718,
    value: "Évora",
    order: 8,
    key: "evora",
    parent: 37,
  },
  {
    id: 9,
    value: "Barcelona",
    order: 9,
    key: "barcelona",
    parent: 17,
  },
  {
    id: 296,
    value: "Champagne - Ardennes",
    order: 9,
    key: "champagne-ardennes",
    parent: 20,
  },
  {
    id: 182,
    value: "Distrito Federal",
    order: 9,
    key: "mexico-distrito-federal",
    parent: 29,
  },
  {
    id: 63,
    value: "Entre Ríos",
    order: 9,
    key: "entre-rios",
    parent: 3,
  },
  {
    id: 240,
    value: "Falcón",
    order: 9,
    key: "falcon",
    parent: 46,
  },
  {
    id: 719,
    value: "Faro",
    order: 9,
    key: "faro",
    parent: 37,
  },
  {
    id: 116,
    value: "Florida",
    order: 9,
    key: "florida",
    parent: 18,
  },
  {
    id: 79,
    value: "Formosa",
    order: 9,
    key: "formosa",
    parent: 3,
  },
  {
    id: 319,
    value: "Genf",
    order: 9,
    key: "genf",
    parent: 44,
  },
  {
    id: 88,
    value: "Goiás",
    order: 9,
    key: "goias",
    parent: 7,
  },
  {
    id: 217,
    value: "Ibague",
    order: 9,
    key: "ibague",
    parent: 11,
  },
  {
    id: 416,
    value: "Kronobergs l??n",
    order: 9,
    key: "kronobergs-lan",
    parent: 43,
  },
  {
    id: 168,
    value: "Magallanes y Antártica Chilena",
    order: 9,
    key: "magallanes-y-antartica-chilena",
    parent: 10,
  },
  {
    id: 265,
    value: "Niedersachsen",
    order: 9,
    key: "niedersachsen",
    parent: 1,
  },
  {
    id: 346,
    value: "Northern Ireland",
    order: 9,
    key: "reino-unido-northern-ireland",
    parent: 39,
  },
  {
    id: 438,
    value: "Oppland",
    order: 9,
    key: "oppland",
    parent: 31,
  },
  {
    id: 474,
    value: "Overijssel",
    order: 9,
    key: "overijssel",
    parent: 23,
  },
  {
    id: 393,
    value: "Ringkj??bing Amt",
    order: 9,
    key: "ringkj-bing-amt",
    parent: 14,
  },
  {
    id: 463,
    value: "Thessaly",
    order: 9,
    key: "thessaly",
    parent: 21,
  },
  {
    id: 362,
    value: "Wien",
    order: 9,
    key: "wien",
    parent: 4,
  },
  {
    id: 609,
    value: "[Calabria] Crotone",
    order: 9,
    key: "calabria-crotone",
    parent: 26,
  },
  {
    id: 10,
    value: "Burgos",
    order: 10,
    key: "burgos",
    parent: 17,
  },
  {
    id: 297,
    value: "Corse",
    order: 10,
    key: "corse",
    parent: 20,
  },
  {
    id: 183,
    value: "Durango",
    order: 10,
    key: "durango",
    parent: 29,
  },
  {
    id: 241,
    value: "Gaurico",
    order: 10,
    key: "gaurico",
    parent: 46,
  },
  {
    id: 117,
    value: "Georgia",
    order: 10,
    key: "estados-unidos-georgia",
    parent: 18,
  },
  {
    id: 320,
    value: "Glarus",
    order: 10,
    key: "glarus",
    parent: 44,
  },
  {
    id: 720,
    value: "Guarda",
    order: 10,
    key: "guarda",
    parent: 37,
  },
  {
    id: 64,
    value: "Jujuy",
    order: 10,
    key: "jujuy",
    parent: 3,
  },
  {
    id: 218,
    value: "Manizales",
    order: 10,
    key: "manizales",
    parent: 11,
  },
  {
    id: 89,
    value: "Maranhao",
    order: 10,
    key: "maranhao",
    parent: 7,
  },
  {
    id: 169,
    value: "Maule",
    order: 10,
    key: "maule",
    parent: 10,
  },
  {
    id: 266,
    value: "Nordrhein - Westfalen",
    order: 10,
    key: "nordrhein-westfalen",
    parent: 1,
  },
  {
    id: 417,
    value: "Norrbottens l??n",
    order: 10,
    key: "norrbottens-lan",
    parent: 43,
  },
  {
    id: 439,
    value: "Oslo m/Akershus",
    order: 10,
    key: "oslo-m-akershus",
    parent: 31,
  },
  {
    id: 394,
    value: "Roskilde Amt",
    order: 10,
    key: "roskilde-amt",
    parent: 14,
  },
  {
    id: 347,
    value: "Scotland",
    order: 10,
    key: "scotland",
    parent: 39,
  },
  {
    id: 464,
    value: "Thrace",
    order: 10,
    key: "thrace",
    parent: 21,
  },
  {
    id: 475,
    value: "Utrecht",
    order: 10,
    key: "utrecht",
    parent: 23,
  },
  {
    id: 610,
    value: "[Calabria] Reggio Calabria",
    order: 10,
    key: "calabria-reggio-calabria",
    parent: 26,
  },
  {
    id: 11,
    value: "Cáceres",
    order: 11,
    key: "caceres",
    parent: 17,
  },
  {
    id: 184,
    value: "Estado de México",
    order: 11,
    key: "estado-de-mexico",
    parent: 29,
  },
  {
    id: 298,
    value: "Franche Comté",
    order: 11,
    key: "franche-comte",
    parent: 20,
  },
  {
    id: 321,
    value: "Graub??nden",
    order: 11,
    key: "graubunden",
    parent: 44,
  },
  {
    id: 118,
    value: "Hawaii",
    order: 11,
    key: "hawaii",
    parent: 18,
  },
  {
    id: 65,
    value: "La Pampa",
    order: 11,
    key: "la-pampa",
    parent: 3,
  },
  {
    id: 242,
    value: "Lara",
    order: 11,
    key: "lara",
    parent: 46,
  },
  {
    id: 721,
    value: "Leiria",
    order: 11,
    key: "leiria",
    parent: 37,
  },
  {
    id: 90,
    value: "Mato Grosso",
    order: 11,
    key: "mato-grosso",
    parent: 7,
  },
  {
    id: 219,
    value: "Medellín",
    order: 11,
    key: "medellin",
    parent: 11,
  },
  {
    id: 267,
    value: "Rheinland - Pfalz",
    order: 11,
    key: "rheinland-pfalz",
    parent: 1,
  },
  {
    id: 440,
    value: "Rogaland",
    order: 11,
    key: "rogaland",
    parent: 31,
  },
  {
    id: 170,
    value: "Santiago",
    order: 11,
    key: "santiago",
    parent: 10,
  },
  {
    id: 418,
    value: "Skåne l??n",
    order: 11,
    key: "sk-ne-lan",
    parent: 43,
  },
  {
    id: 348,
    value: "South East",
    order: 11,
    key: "south-east",
    parent: 39,
  },
  {
    id: 395,
    value: "Storstr??ms Amt",
    order: 11,
    key: "storstr-ms-amt",
    parent: 14,
  },
  {
    id: 476,
    value: "Zeeland",
    order: 11,
    key: "zeeland",
    parent: 23,
  },
  {
    id: 611,
    value: "[Calabria] Vibo Valentia",
    order: 11,
    key: "calabria-vibo-valentia",
    parent: 26,
  },
  {
    id: 12,
    value: "Cádiz",
    order: 12,
    key: "cadiz",
    parent: 17,
  },
  {
    id: 299,
    value: "Haute Normandie",
    order: 12,
    key: "haute-normandie",
    parent: 20,
  },
  {
    id: 119,
    value: "Idaho",
    order: 12,
    key: "idaho",
    parent: 18,
  },
  {
    id: 323,
    value: "Jura",
    order: 12,
    key: "jura",
    parent: 44,
  },
  {
    id: 66,
    value: "La Rioja",
    order: 12,
    key: "argentina-la-rioja",
    parent: 3,
  },
  {
    id: 722,
    value: "Lisboa",
    order: 12,
    key: "lisboa",
    parent: 37,
  },
  {
    id: 91,
    value: "Mato Grosso do Sul",
    order: 12,
    key: "mato-grosso-do-sul",
    parent: 7,
  },
  {
    id: 243,
    value: "Miranda",
    order: 12,
    key: "miranda",
    parent: 46,
  },
  {
    id: 220,
    value: "Montería",
    order: 12,
    key: "monteria",
    parent: 11,
  },
  {
    id: 268,
    value: "Saarland",
    order: 12,
    key: "saarland",
    parent: 1,
  },
  {
    id: 441,
    value: "Sogn og Fjordane",
    order: 12,
    key: "sogn-og-fjordane",
    parent: 31,
  },
  {
    id: 349,
    value: "South West",
    order: 12,
    key: "south-west",
    parent: 39,
  },
  {
    id: 419,
    value: "Stockholms l??n",
    order: 12,
    key: "stockholms-lan",
    parent: 43,
  },
  {
    id: 396,
    value: "S??nderjyllands Amt",
    order: 12,
    key: "s-nderjyllands-amt",
    parent: 14,
  },
  {
    id: 171,
    value: "Tarapacá",
    order: 12,
    key: "tarapaca",
    parent: 10,
  },
  {
    id: 477,
    value: "Zuid Holland",
    order: 12,
    key: "zuid-holland",
    parent: 23,
  },
  {
    id: 612,
    value: "[Campania] Avellino",
    order: 12,
    key: "campania-avellino",
    parent: 26,
  },
  {
    id: 13,
    value: "Cantabria",
    order: 13,
    key: "cantabria",
    parent: 17,
  },
  {
    id: 186,
    value: "Guanajuato",
    order: 13,
    key: "guanajuato",
    parent: 29,
  },
  {
    id: 120,
    value: "Illinois",
    order: 13,
    key: "illinois",
    parent: 18,
  },
  {
    id: 322,
    value: "Luzern",
    order: 13,
    key: "luzern",
    parent: 44,
  },
  {
    id: 723,
    value: "Madeira",
    order: 13,
    key: "madeira",
    parent: 37,
  },
  {
    id: 67,
    value: "Mendoza",
    order: 13,
    key: "mendoza",
    parent: 3,
  },
  {
    id: 92,
    value: "Minas Gerais",
    order: 13,
    key: "minas-gerais",
    parent: 7,
  },
  {
    id: 244,
    value: "Monagas",
    order: 13,
    key: "monagas",
    parent: 46,
  },
  {
    id: 221,
    value: "Neiva",
    order: 13,
    key: "neiva",
    parent: 11,
  },
  {
    id: 269,
    value: "Sachsen",
    order: 13,
    key: "sachsen",
    parent: 1,
  },
  {
    id: 420,
    value: "Södermanlands l??n",
    order: 13,
    key: "sodermanlands-lan",
    parent: 43,
  },
  {
    id: 442,
    value: "S??r - Tr??ndelag",
    order: 13,
    key: "s-r-tr-ndelag",
    parent: 31,
  },
  {
    id: 172,
    value: "Valparaiso",
    order: 13,
    key: "valparaiso",
    parent: 10,
  },
  {
    id: 397,
    value: "Vejle Amt",
    order: 13,
    key: "vejle-amt",
    parent: 14,
  },
  {
    id: 350,
    value: "Wales",
    order: 13,
    key: "wales",
    parent: 39,
  },
  {
    id: 613,
    value: "[Campania] Benevento",
    order: 13,
    key: "campania-benevento",
    parent: 26,
  },
  {
    id: 300,
    value: "Île de France",
    order: 13,
    key: "le-de-france",
    parent: 20,
  },
  {
    id: 14,
    value: "Castellón/Castelló",
    order: 14,
    key: "castellon-castello",
    parent: 17,
  },
  {
    id: 187,
    value: "Guerrero",
    order: 14,
    key: "guerrero",
    parent: 29,
  },
  {
    id: 121,
    value: "Indiana",
    order: 14,
    key: "indiana",
    parent: 18,
  },
  {
    id: 301,
    value: "Languedoc - Roussillon",
    order: 14,
    key: "languedoc-roussillon",
    parent: 20,
  },
  {
    id: 68,
    value: "Misiones",
    order: 14,
    key: "misiones",
    parent: 3,
  },
  {
    id: 245,
    value: "Mérida",
    order: 14,
    key: "merida",
    parent: 46,
  },
  {
    id: 324,
    value: "Neuenburg",
    order: 14,
    key: "neuenburg",
    parent: 44,
  },
  {
    id: 93,
    value: "Pará",
    order: 14,
    key: "para",
    parent: 7,
  },
  {
    id: 222,
    value: "Pasto",
    order: 14,
    key: "pasto",
    parent: 11,
  },
  {
    id: 724,
    value: "Portalegre",
    order: 14,
    key: "portalegre",
    parent: 37,
  },
  {
    id: 270,
    value: "Sachsen - Anhalt",
    order: 14,
    key: "sachsen-anhalt",
    parent: 1,
  },
  {
    id: 443,
    value: "Telemark",
    order: 14,
    key: "telemark",
    parent: 31,
  },
  {
    id: 421,
    value: "Uppsala l??n",
    order: 14,
    key: "uppsala-lan",
    parent: 43,
  },
  {
    id: 398,
    value: "Vestsj??llands Amt",
    order: 14,
    key: "vestsj-llands-amt",
    parent: 14,
  },
  {
    id: 351,
    value: "West Midlands",
    order: 14,
    key: "west-midlands",
    parent: 39,
  },
  {
    id: 614,
    value: "[Campania] Caserta",
    order: 14,
    key: "campania-caserta",
    parent: 26,
  },
  {
    id: 15,
    value: "Ceuta",
    order: 15,
    key: "ceuta",
    parent: 17,
  },
  {
    id: 188,
    value: "Hidalgo",
    order: 15,
    key: "hidalgo",
    parent: 29,
  },
  {
    id: 122,
    value: "Iowa",
    order: 15,
    key: "iowa",
    parent: 18,
  },
  {
    id: 302,
    value: "Limousin",
    order: 15,
    key: "limousin",
    parent: 20,
  },
  {
    id: 69,
    value: "Neuquén",
    order: 15,
    key: "neuquen",
    parent: 3,
  },
  {
    id: 325,
    value: "Nidwalden",
    order: 15,
    key: "nidwalden",
    parent: 44,
  },
  {
    id: 246,
    value: "Nueva Esparta",
    order: 15,
    key: "nueva-esparta",
    parent: 46,
  },
  {
    id: 94,
    value: "Paraíba",
    order: 15,
    key: "paraiba",
    parent: 7,
  },
  {
    id: 223,
    value: "Pereira",
    order: 15,
    key: "pereira",
    parent: 11,
  },
  {
    id: 725,
    value: "Porto",
    order: 15,
    key: "porto",
    parent: 37,
  },
  {
    id: 271,
    value: "Schleswig - Holstein",
    order: 15,
    key: "schleswig-holstein",
    parent: 1,
  },
  {
    id: 444,
    value: "Troms",
    order: 15,
    key: "troms",
    parent: 31,
  },
  {
    id: 399,
    value: "Viborg Amt",
    order: 15,
    key: "viborg-amt",
    parent: 14,
  },
  {
    id: 422,
    value: "V??rmlands l??n",
    order: 15,
    key: "varmlands-lan",
    parent: 43,
  },
  {
    id: 352,
    value: "Yorkshire",
    order: 15,
    key: "yorkshire",
    parent: 39,
  },
  {
    id: 615,
    value: "[Campania] Nápoles",
    order: 15,
    key: "campania-napoles",
    parent: 26,
  },
  {
    id: 16,
    value: "Ciudad Real",
    order: 16,
    key: "ciudad-real",
    parent: 17,
  },
  {
    id: 189,
    value: "Jalisco",
    order: 16,
    key: "jalisco",
    parent: 29,
  },
  {
    id: 123,
    value: "Kansas",
    order: 16,
    key: "kansas",
    parent: 18,
  },
  {
    id: 303,
    value: "Lorraine",
    order: 16,
    key: "lorraine",
    parent: 20,
  },
  {
    id: 326,
    value: "Obwalden",
    order: 16,
    key: "obwalden",
    parent: 44,
  },
  {
    id: 95,
    value: "Paraná",
    order: 16,
    key: "parana",
    parent: 7,
  },
  {
    id: 224,
    value: "Popayán",
    order: 16,
    key: "popayan",
    parent: 11,
  },
  {
    id: 247,
    value: "Portuguesa",
    order: 16,
    key: "portuguesa",
    parent: 46,
  },
  {
    id: 70,
    value: "Río Negro",
    order: 16,
    key: "rio-negro",
    parent: 3,
  },
  {
    id: 726,
    value: "Santarém",
    order: 16,
    key: "santarem",
    parent: 37,
  },
  {
    id: 272,
    value: "Th??ringen",
    order: 16,
    key: "thuringen",
    parent: 1,
  },
  {
    id: 445,
    value: "Vest Agder",
    order: 16,
    key: "vest-agder",
    parent: 31,
  },
  {
    id: 423,
    value: "V??rstenbottens l??n",
    order: 16,
    key: "varstenbottens-lan",
    parent: 43,
  },
  {
    id: 616,
    value: "[Campania] Salerno",
    order: 16,
    key: "campania-salerno",
    parent: 26,
  },
  {
    id: 400,
    value: "Århus Amt",
    order: 16,
    key: "rhus-amt",
    parent: 14,
  },
  {
    id: 17,
    value: "Córdoba",
    order: 17,
    key: "cordoba",
    parent: 17,
  },
  {
    id: 124,
    value: "Kentucky",
    order: 17,
    key: "kentucky",
    parent: 18,
  },
  {
    id: 190,
    value: "Michoacán",
    order: 17,
    key: "michoacan",
    parent: 29,
  },
  {
    id: 304,
    value: "Midi - Pyrénées",
    order: 17,
    key: "midi-pyrenees",
    parent: 20,
  },
  {
    id: 96,
    value: "Pernambuco",
    order: 17,
    key: "pernambuco",
    parent: 7,
  },
  {
    id: 71,
    value: "Salta",
    order: 17,
    key: "salta",
    parent: 3,
  },
  {
    id: 225,
    value: "Santa Marta",
    order: 17,
    key: "santa-marta",
    parent: 11,
  },
  {
    id: 337,
    value: "Schaffhausen",
    order: 17,
    key: "schaffhausen",
    parent: 44,
  },
  {
    id: 727,
    value: "Setúbal",
    order: 17,
    key: "setubal",
    parent: 37,
  },
  {
    id: 248,
    value: "Sucre",
    order: 17,
    key: "sucre",
    parent: 46,
  },
  {
    id: 446,
    value: "Vestfold",
    order: 17,
    key: "vestfold",
    parent: 31,
  },
  {
    id: 424,
    value: "V??rsternorrlands l??n",
    order: 17,
    key: "varsternorrlands-lan",
    parent: 43,
  },
  {
    id: 617,
    value: "[Emilia-Romaña] Bolonia",
    order: 17,
    key: "emilia-romana-bolonia",
    parent: 26,
  },
  {
    id: 18,
    value: "Cuenca",
    order: 18,
    key: "cuenca",
    parent: 17,
  },
  {
    id: 125,
    value: "Louisiana",
    order: 18,
    key: "louisiana",
    parent: 18,
  },
  {
    id: 305,
    value: "Nord Pas de Calais",
    order: 18,
    key: "nord-pas-de-calais",
    parent: 20,
  },
  {
    id: 97,
    value: "Piauí",
    order: 18,
    key: "piaui",
    parent: 7,
  },
  {
    id: 72,
    value: "San Juan",
    order: 18,
    key: "san-juan",
    parent: 3,
  },
  {
    id: 329,
    value: "Schwyz",
    order: 18,
    key: "schwyz",
    parent: 44,
  },
  {
    id: 226,
    value: "Sincelejo",
    order: 18,
    key: "sincelejo",
    parent: 11,
  },
  {
    id: 249,
    value: "Trujillo",
    order: 18,
    key: "trujillo",
    parent: 46,
  },
  {
    id: 728,
    value: "Viana do Castelo",
    order: 18,
    key: "viana-do-castelo",
    parent: 37,
  },
  {
    id: 425,
    value: "V??stmanlands l??n",
    order: 18,
    key: "vastmanlands-lan",
    parent: 43,
  },
  {
    id: 618,
    value: "[Emilia-Romaña] Ferrara",
    order: 18,
    key: "emilia-romana-ferrara",
    parent: 26,
  },
  {
    id: 447,
    value: "Østfold",
    order: 18,
    key: "stfold",
    parent: 31,
  },
  {
    id: 19,
    value: "Girona",
    order: 19,
    key: "girona",
    parent: 17,
  },
  {
    id: 126,
    value: "Maine",
    order: 19,
    key: "maine",
    parent: 18,
  },
  {
    id: 192,
    value: "Morelos",
    order: 19,
    key: "morelos",
    parent: 29,
  },
  {
    id: 306,
    value: "Pays de la Loire",
    order: 19,
    key: "pays-de-la-loire",
    parent: 20,
  },
  {
    id: 98,
    value: "Rio de Janeiro",
    order: 19,
    key: "rio-de-janeiro",
    parent: 7,
  },
  {
    id: 73,
    value: "San Luís",
    order: 19,
    key: "san-luis",
    parent: 3,
  },
  {
    id: 328,
    value: "Solothurn",
    order: 19,
    key: "solothurn",
    parent: 44,
  },
  {
    id: 227,
    value: "Tunja",
    order: 19,
    key: "tunja",
    parent: 11,
  },
  {
    id: 250,
    value: "Táchira",
    order: 19,
    key: "tachira",
    parent: 46,
  },
  {
    id: 729,
    value: "Vila Real",
    order: 19,
    key: "vila-real",
    parent: 37,
  },
  {
    id: 426,
    value: "V??stra Götalands l??n",
    order: 19,
    key: "vastra-gotalands-lan",
    parent: 43,
  },
  {
    id: 619,
    value: "[Emilia-Romaña] Forlì-Cesena",
    order: 19,
    key: "emilia-romana-forli-cesena",
    parent: 26,
  },
  {
    id: 21,
    value: "Granada",
    order: 20,
    key: "granada",
    parent: 17,
  },
  {
    id: 127,
    value: "Maryland",
    order: 20,
    key: "maryland",
    parent: 18,
  },
  {
    id: 193,
    value: "Nayarit",
    order: 20,
    key: "nayarit",
    parent: 29,
  },
  {
    id: 307,
    value: "Picardie",
    order: 20,
    key: "picardie",
    parent: 20,
  },
  {
    id: 99,
    value: "Rio Grande do Norte",
    order: 20,
    key: "rio-grande-do-norte",
    parent: 7,
  },
  {
    id: 74,
    value: "Santa Cruz",
    order: 20,
    key: "santa-cruz",
    parent: 3,
  },
  {
    id: 327,
    value: "St. Gallen",
    order: 20,
    key: "st.-gallen",
    parent: 44,
  },
  {
    id: 228,
    value: "Valledupar",
    order: 20,
    key: "valledupar",
    parent: 11,
  },
  {
    id: 251,
    value: "Vargas",
    order: 20,
    key: "vargas",
    parent: 46,
  },
  {
    id: 730,
    value: "Viseu",
    order: 20,
    key: "viseu",
    parent: 37,
  },
  {
    id: 620,
    value: "[Emilia-Romaña] Módena",
    order: 20,
    key: "emilia-romana-modena",
    parent: 26,
  },
  {
    id: 427,
    value: "Örebro l??n",
    order: 20,
    key: "orebro-lan",
    parent: 43,
  },
  {
    id: 731,
    value: "Angola",
    order: 21,
    key: "angola",
    parent: 37,
  },
  {
    id: 22,
    value: "Guadalajara",
    order: 21,
    key: "guadalajara",
    parent: 17,
  },
  {
    id: 128,
    value: "Massachusetts",
    order: 21,
    key: "massachusetts",
    parent: 18,
  },
  {
    id: 194,
    value: "Nuevo León",
    order: 21,
    key: "nuevo-leon",
    parent: 29,
  },
  {
    id: 308,
    value: "Poitou - Charentes",
    order: 21,
    key: "poitou-charentes",
    parent: 20,
  },
  {
    id: 100,
    value: "Rio Grande do Sul",
    order: 21,
    key: "rio-grande-do-sul",
    parent: 7,
  },
  {
    id: 75,
    value: "Santa Fe",
    order: 21,
    key: "santa-fe",
    parent: 3,
  },
  {
    id: 330,
    value: "Thurgau",
    order: 21,
    key: "thurgau",
    parent: 44,
  },
  {
    id: 229,
    value: "Villavicencio",
    order: 21,
    key: "villavicencio",
    parent: 11,
  },
  {
    id: 252,
    value: "Yaracuy",
    order: 21,
    key: "yaracuy",
    parent: 46,
  },
  {
    id: 621,
    value: "[Emilia-Romaña] Parma",
    order: 21,
    key: "emilia-romana-parma",
    parent: 26,
  },
  {
    id: 428,
    value: "Östergötlands l??n",
    order: 21,
    key: "ostergotlands-lan",
    parent: 43,
  },
  {
    id: 23,
    value: "Guipúzcoa/Gipuzkoa",
    order: 22,
    key: "guipuzcoa-gipuzkoa",
    parent: 17,
  },
  {
    id: 129,
    value: "Michigan",
    order: 22,
    key: "michigan",
    parent: 18,
  },
  {
    id: 195,
    value: "Oaxaca",
    order: 22,
    key: "oaxaca",
    parent: 29,
  },
  {
    id: 309,
    value: "Provence - Alpes - C??te d'Azur",
    order: 22,
    key: "provence-alpes-c-te-d-azur",
    parent: 20,
  },
  {
    id: 101,
    value: "Rondonia",
    order: 22,
    key: "rondonia",
    parent: 7,
  },
  {
    id: 76,
    value: "Santiago del Estero",
    order: 22,
    key: "santiago-del-estero",
    parent: 3,
  },
  {
    id: 332,
    value: "Uri",
    order: 22,
    key: "uri",
    parent: 44,
  },
  {
    id: 230,
    value: "Yumbo",
    order: 22,
    key: "yumbo",
    parent: 11,
  },
  {
    id: 253,
    value: "Zulia",
    order: 22,
    key: "zulia",
    parent: 46,
  },
  {
    id: 622,
    value: "[Emilia-Romaña] Piacenza",
    order: 22,
    key: "emilia-romana-piacenza",
    parent: 26,
  },
  {
    id: 24,
    value: "Huelva",
    order: 23,
    key: "huelva",
    parent: 17,
  },
  {
    id: 130,
    value: "Minnesota",
    order: 23,
    key: "minnesota",
    parent: 18,
  },
  {
    id: 196,
    value: "Puebla",
    order: 23,
    key: "puebla",
    parent: 29,
  },
  {
    id: 310,
    value: "Rh??ne Alpes",
    order: 23,
    key: "rh-ne-alpes",
    parent: 20,
  },
  {
    id: 102,
    value: "Roraina",
    order: 23,
    key: "roraina",
    parent: 7,
  },
  {
    id: 77,
    value: "Tierra del Fuego",
    order: 23,
    key: "tierra-del-fuego",
    parent: 3,
  },
  {
    id: 333,
    value: "Waadt",
    order: 23,
    key: "waadt",
    parent: 44,
  },
  {
    id: 623,
    value: "[Emilia-Romaña] Rávena",
    order: 23,
    key: "emilia-romana-ravena",
    parent: 26,
  },
  {
    id: 25,
    value: "Huesca",
    order: 24,
    key: "huesca",
    parent: 17,
  },
  {
    id: 131,
    value: "Mississippi",
    order: 24,
    key: "mississippi",
    parent: 18,
  },
  {
    id: 197,
    value: "Querétaro",
    order: 24,
    key: "queretaro",
    parent: 29,
  },
  {
    id: 103,
    value: "Santa Catarina",
    order: 24,
    key: "santa-catarina",
    parent: 7,
  },
  {
    id: 78,
    value: "Tucumán",
    order: 24,
    key: "tucuman",
    parent: 3,
  },
  {
    id: 334,
    value: "Wallis",
    order: 24,
    key: "wallis",
    parent: 44,
  },
  {
    id: 624,
    value: "[Emilia-Romaña] Reggio Emilia",
    order: 24,
    key: "emilia-romana-reggio-emilia",
    parent: 26,
  },
  {
    id: 26,
    value: "Islas Baleares/Illes Balears",
    order: 25,
    key: "illes-balears",
    parent: 17,
  },
  {
    id: 132,
    value: "Missouri",
    order: 25,
    key: "missouri",
    parent: 18,
  },
  {
    id: 198,
    value: "Quintana Roo",
    order: 25,
    key: "quintana-roo",
    parent: 29,
  },
  {
    id: 104,
    value: "Sergipe",
    order: 25,
    key: "sergipe",
    parent: 7,
  },
  {
    id: 335,
    value: "Zug",
    order: 25,
    key: "zug",
    parent: 44,
  },
  {
    id: 625,
    value: "[Emilia-Romaña] Rímini",
    order: 25,
    key: "emilia-romana-rimini",
    parent: 26,
  },
  {
    id: 27,
    value: "Jaén",
    order: 26,
    key: "jaen",
    parent: 17,
  },
  {
    id: 133,
    value: "Montana",
    order: 26,
    key: "montana",
    parent: 18,
  },
  {
    id: 199,
    value: "San Luís Potosí",
    order: 26,
    key: "san-luis-potosi",
    parent: 29,
  },
  {
    id: 105,
    value: "Sao Paulo",
    order: 26,
    key: "sao-paulo",
    parent: 7,
  },
  {
    id: 336,
    value: "Z??rich",
    order: 26,
    key: "zurich",
    parent: 44,
  },
  {
    id: 626,
    value: "[Friuli-Venecia Julia] Gorizia",
    order: 26,
    key: "friuli-venecia-julia-gorizia",
    parent: 26,
  },
  {
    id: 29,
    value: "La Rioja",
    order: 27,
    key: "la-rioja",
    parent: 17,
  },
  {
    id: 134,
    value: "Nebraska",
    order: 27,
    key: "nebraska",
    parent: 18,
  },
  {
    id: 200,
    value: "Sinaloa",
    order: 27,
    key: "sinaloa",
    parent: 29,
  },
  {
    id: 106,
    value: "Tocantins",
    order: 27,
    key: "tocantins",
    parent: 7,
  },
  {
    id: 627,
    value: "[Friuli-Venecia Julia] Pordenone",
    order: 27,
    key: "friuli-venecia-julia-pordenone",
    parent: 26,
  },
  {
    id: 20,
    value: "Las Palmas",
    order: 28,
    key: "las-palmas",
    parent: 17,
  },
  {
    id: 135,
    value: "Nevada",
    order: 28,
    key: "nevada",
    parent: 18,
  },
  {
    id: 201,
    value: "Sonora",
    order: 28,
    key: "sonora",
    parent: 29,
  },
  {
    id: 628,
    value: "[Friuli-Venecia Julia] Trieste",
    order: 28,
    key: "friuli-venecia-julia-trieste",
    parent: 26,
  },
  {
    id: 30,
    value: "León",
    order: 29,
    key: "leon",
    parent: 17,
  },
  {
    id: 136,
    value: "New Hampshire",
    order: 29,
    key: "new-hampshire",
    parent: 18,
  },
  {
    id: 202,
    value: "Tabasco",
    order: 29,
    key: "tabasco",
    parent: 29,
  },
  {
    id: 629,
    value: "[Friuli-Venecia Julia] Udine",
    order: 29,
    key: "friuli-venecia-julia-udine",
    parent: 26,
  },
  {
    id: 31,
    value: "Lleida",
    order: 30,
    key: "lleida",
    parent: 17,
  },
  {
    id: 137,
    value: "New Jersey",
    order: 30,
    key: "new-jersey",
    parent: 18,
  },
  {
    id: 203,
    value: "Tamaulipas",
    order: 30,
    key: "tamaulipas",
    parent: 29,
  },
  {
    id: 630,
    value: "[Lacio] Frosinone",
    order: 30,
    key: "lacio-frosinone",
    parent: 26,
  },
  {
    id: 32,
    value: "Lugo",
    order: 31,
    key: "lugo",
    parent: 17,
  },
  {
    id: 138,
    value: "New Mexico",
    order: 31,
    key: "new-mexico",
    parent: 18,
  },
  {
    id: 204,
    value: "Tlaxcala",
    order: 31,
    key: "tlaxcala",
    parent: 29,
  },
  {
    id: 631,
    value: "[Lacio] Latina",
    order: 31,
    key: "lacio-latina",
    parent: 26,
  },
  {
    id: 33,
    value: "Madrid",
    order: 32,
    key: "madrid",
    parent: 17,
  },
  {
    id: 139,
    value: "New York",
    order: 32,
    key: "new-york",
    parent: 18,
  },
  {
    id: 205,
    value: "Veracruz",
    order: 32,
    key: "veracruz",
    parent: 29,
  },
  {
    id: 632,
    value: "[Lacio] Rieti",
    order: 32,
    key: "lacio-rieti",
    parent: 26,
  },
  {
    id: 34,
    value: "Málaga",
    order: 33,
    key: "malaga",
    parent: 17,
  },
  {
    id: 140,
    value: "North Carolina",
    order: 33,
    key: "north-carolina",
    parent: 18,
  },
  {
    id: 206,
    value: "Yucatán",
    order: 33,
    key: "yucatan",
    parent: 29,
  },
  {
    id: 633,
    value: "[Lacio] Roma",
    order: 33,
    key: "lacio-roma",
    parent: 26,
  },
  {
    id: 35,
    value: "Melilla",
    order: 34,
    key: "melilla",
    parent: 17,
  },
  {
    id: 141,
    value: "North Dakota",
    order: 34,
    key: "north-dakota",
    parent: 18,
  },
  {
    id: 207,
    value: "Zacatecas",
    order: 34,
    key: "zacatecas",
    parent: 29,
  },
  {
    id: 634,
    value: "[Lacio] Viterbo",
    order: 34,
    key: "lacio-viterbo",
    parent: 26,
  },
  {
    id: 36,
    value: "Murcia",
    order: 35,
    key: "murcia",
    parent: 17,
  },
  {
    id: 142,
    value: "Ohio",
    order: 35,
    key: "ohio",
    parent: 18,
  },
  {
    id: 635,
    value: "[Liguria] Génova",
    order: 35,
    key: "liguria-genova",
    parent: 26,
  },
  {
    id: 37,
    value: "Navarra",
    order: 36,
    key: "navarra",
    parent: 17,
  },
  {
    id: 143,
    value: "Oklahoma",
    order: 36,
    key: "oklahoma",
    parent: 18,
  },
  {
    id: 636,
    value: "[Liguria] Imperia",
    order: 36,
    key: "liguria-imperia",
    parent: 26,
  },
  {
    id: 144,
    value: "Oregon",
    order: 37,
    key: "oregon",
    parent: 18,
  },
  {
    id: 38,
    value: "Ourense",
    order: 37,
    key: "ourense",
    parent: 17,
  },
  {
    id: 637,
    value: "[Liguria] La Spezia",
    order: 37,
    key: "liguria-la-spezia",
    parent: 26,
  },
  {
    id: 39,
    value: "Palencia",
    order: 38,
    key: "palencia",
    parent: 17,
  },
  {
    id: 145,
    value: "Pennsylvania",
    order: 38,
    key: "pennsylvania",
    parent: 18,
  },
  {
    id: 638,
    value: "[Liguria] Savona",
    order: 38,
    key: "liguria-savona",
    parent: 26,
  },
  {
    id: 40,
    value: "Pontevedra",
    order: 39,
    key: "pontevedra",
    parent: 17,
  },
  {
    id: 146,
    value: "Rhode Island",
    order: 39,
    key: "rhode-island",
    parent: 18,
  },
  {
    id: 639,
    value: "[Lombardía] Bérgamo",
    order: 39,
    key: "lombardia-bergamo",
    parent: 26,
  },
  {
    id: 41,
    value: "Salamanca",
    order: 40,
    key: "salamanca",
    parent: 17,
  },
  {
    id: 147,
    value: "South Carolina",
    order: 40,
    key: "south-carolina",
    parent: 18,
  },
  {
    id: 640,
    value: "[Lombardía] Brescia",
    order: 40,
    key: "lombardia-brescia",
    parent: 26,
  },
  {
    id: 46,
    value: "Santa Cruz de Tenerife",
    order: 41,
    key: "santa-cruz-de-tenerife",
    parent: 17,
  },
  {
    id: 148,
    value: "South Dakota",
    order: 41,
    key: "south-dakota",
    parent: 18,
  },
  {
    id: 641,
    value: "[Lombardía] Como",
    order: 41,
    key: "lombardia-como",
    parent: 26,
  },
  {
    id: 42,
    value: "Segovia",
    order: 42,
    key: "segovia",
    parent: 17,
  },
  {
    id: 149,
    value: "Tennessee",
    order: 42,
    key: "tennessee",
    parent: 18,
  },
  {
    id: 642,
    value: "[Lombardía] Cremona",
    order: 42,
    key: "lombardia-cremona",
    parent: 26,
  },
  {
    id: 43,
    value: "Sevilla",
    order: 43,
    key: "sevilla",
    parent: 17,
  },
  {
    id: 150,
    value: "Texas",
    order: 43,
    key: "texas",
    parent: 18,
  },
  {
    id: 643,
    value: "[Lombardía] Lecco",
    order: 43,
    key: "lombardia-lecco",
    parent: 26,
  },
  {
    id: 44,
    value: "Soria",
    order: 44,
    key: "soria",
    parent: 17,
  },
  {
    id: 151,
    value: "Utah",
    order: 44,
    key: "utah",
    parent: 18,
  },
  {
    id: 644,
    value: "[Lombardía] Lodi",
    order: 44,
    key: "lombardia-lodi",
    parent: 26,
  },
  {
    id: 45,
    value: "Tarragona",
    order: 45,
    key: "tarragona",
    parent: 17,
  },
  {
    id: 152,
    value: "Vermont",
    order: 45,
    key: "vermont",
    parent: 18,
  },
  {
    id: 645,
    value: "[Lombardía] Mantua",
    order: 45,
    key: "lombardia-mantua",
    parent: 26,
  },
  {
    id: 47,
    value: "Teruel",
    order: 46,
    key: "teruel",
    parent: 17,
  },
  {
    id: 153,
    value: "Virginia",
    order: 46,
    key: "virginia",
    parent: 18,
  },
  {
    id: 646,
    value: "[Lombardía] Monza y Brianza",
    order: 46,
    key: "lombardia-monza-y-brianza",
    parent: 26,
  },
  {
    id: 48,
    value: "Toledo",
    order: 47,
    key: "toledo",
    parent: 17,
  },
  {
    id: 154,
    value: "Washington",
    order: 47,
    key: "washington",
    parent: 18,
  },
  {
    id: 647,
    value: "[Lombardía] Milán",
    order: 47,
    key: "lombardia-milan",
    parent: 26,
  },
  {
    id: 49,
    value: "Valencia/Val??ncia",
    order: 48,
    key: "valencia-valencia",
    parent: 17,
  },
  {
    id: 155,
    value: "Washington, D.C.",
    order: 48,
    key: "washington-d.c.",
    parent: 18,
  },
  {
    id: 648,
    value: "[Lombardía] Pavía",
    order: 48,
    key: "lombardia-pavia",
    parent: 26,
  },
  {
    id: 50,
    value: "Valladolid",
    order: 49,
    key: "valladolid",
    parent: 17,
  },
  {
    id: 156,
    value: "West Virginia",
    order: 49,
    key: "west-virginia",
    parent: 18,
  },
  {
    id: 649,
    value: "[Lombardía] Sondrio",
    order: 49,
    key: "lombardia-sondrio",
    parent: 26,
  },
  {
    id: 51,
    value: "Vizcaya/Bizkaia",
    order: 50,
    key: "vizcaya-bizkaia",
    parent: 17,
  },
  {
    id: 157,
    value: "Wisconsin",
    order: 50,
    key: "wisconsin",
    parent: 18,
  },
  {
    id: 650,
    value: "[Lombardía] Varese",
    order: 50,
    key: "lombardia-varese",
    parent: 26,
  },
  {
    id: 158,
    value: "Wyoming",
    order: 51,
    key: "wyoming",
    parent: 18,
  },
  {
    id: 52,
    value: "Zamora",
    order: 51,
    key: "zamora",
    parent: 17,
  },
  {
    id: 651,
    value: "[Marcas] Ancona",
    order: 51,
    key: "marcas-ancona",
    parent: 26,
  },
  {
    id: 53,
    value: "Zaragoza",
    order: 52,
    key: "zaragoza",
    parent: 17,
  },
  {
    id: 652,
    value: "[Marcas] Ascoli Piceno",
    order: 52,
    key: "marcas-ascoli-piceno",
    parent: 26,
  },
  {
    id: 559,
    value: "Chipre",
    order: 53,
    key: "chipre",
    parent: 65,
  },
  {
    id: 653,
    value: "[Marcas] Fermo",
    order: 53,
    key: "marcas-fermo",
    parent: 26,
  },
  {
    id: 561,
    value: "Eslovenia",
    order: 54,
    key: "eslovenia",
    parent: 66,
  },
  {
    id: 654,
    value: "[Marcas] Macerata",
    order: 54,
    key: "marcas-macerata",
    parent: 26,
  },
  {
    id: 563,
    value: "Letonia",
    order: 55,
    key: "letonia",
    parent: 68,
  },
  {
    id: 655,
    value: "[Marcas] Pesaro y Urbino",
    order: 55,
    key: "marcas-pesaro-y-urbino",
    parent: 26,
  },
  {
    id: 565,
    value: "Lituania",
    order: 56,
    key: "lituania",
    parent: 69,
  },
  {
    id: 656,
    value: "[Molise] Campobasso",
    order: 56,
    key: "molise-campobasso",
    parent: 26,
  },
  {
    id: 567,
    value: "Malta",
    order: 57,
    key: "malta",
    parent: 70,
  },
  {
    id: 657,
    value: "[Molise] Isernia",
    order: 57,
    key: "molise-isernia",
    parent: 26,
  },
  {
    id: 569,
    value: "República Eslovaca",
    order: 58,
    key: "republica-eslovaca",
    parent: 71,
  },
  {
    id: 658,
    value: "[Piamonte] Alessandria",
    order: 58,
    key: "piamonte-alessandria",
    parent: 26,
  },
  {
    id: 571,
    value: "Estonia",
    order: 59,
    key: "estonia",
    parent: 67,
  },
  {
    id: 659,
    value: "[Piamonte] Asti",
    order: 59,
    key: "piamonte-asti",
    parent: 26,
  },
  {
    id: 572,
    value: "Albania",
    order: 60,
    key: "albania",
    parent: 72,
  },
  {
    id: 660,
    value: "[Piamonte] Biella",
    order: 60,
    key: "piamonte-biella",
    parent: 26,
  },
  {
    id: 573,
    value: "Bielorrusia",
    order: 61,
    key: "bielorrusia",
    parent: 73,
  },
  {
    id: 661,
    value: "[Piamonte] Cuneo",
    order: 61,
    key: "piamonte-cuneo",
    parent: 26,
  },
  {
    id: 574,
    value: "Bosnia-Herzegovina",
    order: 62,
    key: "bosnia-herzegovina",
    parent: 74,
  },
  {
    id: 662,
    value: "[Piamonte] Novara",
    order: 62,
    key: "piamonte-novara",
    parent: 26,
  },
  {
    id: 575,
    value: "Macedonia",
    order: 63,
    key: "republica-de-macedonia-macedonia",
    parent: 75,
  },
  {
    id: 663,
    value: "[Piamonte] Turín",
    order: 63,
    key: "piamonte-turin",
    parent: 26,
  },
  {
    id: 576,
    value: "Moldavia",
    order: 64,
    key: "moldavia",
    parent: 76,
  },
  {
    id: 577,
    value: "Mónaco",
    order: 64,
    key: "monaco",
    parent: 77,
  },
  {
    id: 664,
    value: "[Piamonte] Verbano-Cusio-Ossola",
    order: 64,
    key: "piamonte-verbano-cusio-ossola",
    parent: 26,
  },
  {
    id: 578,
    value: "San Marino",
    order: 65,
    key: "san-marino",
    parent: 78,
  },
  {
    id: 665,
    value: "[Piamonte] Vercelli",
    order: 65,
    key: "piamonte-vercelli",
    parent: 26,
  },
  {
    id: 579,
    value: "Turquía",
    order: 66,
    key: "turquia",
    parent: 79,
  },
  {
    id: 666,
    value: "[Apulia] Bari",
    order: 66,
    key: "apulia-bari",
    parent: 26,
  },
  {
    id: 580,
    value: "Ucrania",
    order: 67,
    key: "ucrania",
    parent: 80,
  },
  {
    id: 667,
    value: "[Apulia] Barletta-Andria-Trani",
    order: 67,
    key: "apulia-barletta-andria-trani",
    parent: 26,
  },
  {
    id: 581,
    value: "Ciudad del Vaticano",
    order: 68,
    key: "ciudad-del-vaticano",
    parent: 81,
  },
  {
    id: 668,
    value: "[Apulia] Brindisi",
    order: 68,
    key: "apulia-brindisi",
    parent: 26,
  },
  {
    id: 582,
    value: "Croacia",
    order: 69,
    key: "croacia",
    parent: 82,
  },
  {
    id: 669,
    value: "[Apulia] Foggia",
    order: 69,
    key: "apulia-foggia",
    parent: 26,
  },
  {
    id: 670,
    value: "[Apulia] Lecce",
    order: 70,
    key: "apulia-lecce",
    parent: 26,
  },
  {
    id: 671,
    value: "[Apulia] Tarento",
    order: 71,
    key: "apulia-tarento",
    parent: 26,
  },
  {
    id: 672,
    value: "[Cerdeña] Cagliari",
    order: 72,
    key: "cerdena-cagliari",
    parent: 26,
  },
  {
    id: 673,
    value: "[Cerdeña] Carbonia-Iglesias",
    order: 73,
    key: "cerdena-carbonia-iglesias",
    parent: 26,
  },
  {
    id: 674,
    value: "[Cerdeña] Medio Campidano",
    order: 74,
    key: "cerdena-medio-campidano",
    parent: 26,
  },
  {
    id: 675,
    value: "[Cerdeña] Nuoro",
    order: 75,
    key: "cerdena-nuoro",
    parent: 26,
  },
  {
    id: 676,
    value: "[Cerdeña] Ogliastra",
    order: 76,
    key: "cerdena-ogliastra",
    parent: 26,
  },
  {
    id: 677,
    value: "[Cerdeña] Olbia-Tempio",
    order: 77,
    key: "cerdena-olbia-tempio",
    parent: 26,
  },
  {
    id: 678,
    value: "[Cerdeña] Oristano",
    order: 78,
    key: "cerdena-oristano",
    parent: 26,
  },
  {
    id: 679,
    value: "[Cerdeña] Sassari",
    order: 79,
    key: "cerdena-sassari",
    parent: 26,
  },
  {
    id: 680,
    value: "[Sicilia] Agrigento",
    order: 80,
    key: "sicilia-agrigento",
    parent: 26,
  },
  {
    id: 681,
    value: "[Sicilia] Caltanissetta",
    order: 81,
    key: "sicilia-caltanissetta",
    parent: 26,
  },
  {
    id: 682,
    value: "[Sicilia] Catania",
    order: 82,
    key: "sicilia-catania",
    parent: 26,
  },
  {
    id: 683,
    value: "[Sicilia] Enna",
    order: 83,
    key: "sicilia-enna",
    parent: 26,
  },
  {
    id: 684,
    value: "[Sicilia] Messina",
    order: 84,
    key: "sicilia-messina",
    parent: 26,
  },
  {
    id: 685,
    value: "[Sicilia] Palermo",
    order: 85,
    key: "sicilia-palermo",
    parent: 26,
  },
  {
    id: 686,
    value: "[Sicilia] Ragusa",
    order: 86,
    key: "sicilia-ragusa",
    parent: 26,
  },
  {
    id: 687,
    value: "[Sicilia] Siracusa",
    order: 87,
    key: "sicilia-siracusa",
    parent: 26,
  },
  {
    id: 688,
    value: "[Sicilia] Trapani",
    order: 88,
    key: "sicilia-trapani",
    parent: 26,
  },
  {
    id: 689,
    value: "[Toscana] Arezzo",
    order: 89,
    key: "toscana-arezzo",
    parent: 26,
  },
  {
    id: 690,
    value: "[Toscana] Florencia",
    order: 90,
    key: "toscana-florencia",
    parent: 26,
  },
  {
    id: 691,
    value: "[Toscana] Grosseto",
    order: 91,
    key: "toscana-grosseto",
    parent: 26,
  },
  {
    id: 692,
    value: "[Toscana] Livorno",
    order: 92,
    key: "toscana-livorno",
    parent: 26,
  },
  {
    id: 693,
    value: "[Toscana] Lucca",
    order: 93,
    key: "toscana-lucca",
    parent: 26,
  },
  {
    id: 694,
    value: "[Toscana] Massa Carrara",
    order: 94,
    key: "toscana-massa-carrara",
    parent: 26,
  },
  {
    id: 695,
    value: "[Toscana] Pisa",
    order: 95,
    key: "toscana-pisa",
    parent: 26,
  },
  {
    id: 696,
    value: "[Toscana] Pistoia",
    order: 96,
    key: "toscana-pistoia",
    parent: 26,
  },
  {
    id: 697,
    value: "[Toscana] Prato",
    order: 97,
    key: "toscana-prato",
    parent: 26,
  },
  {
    id: 698,
    value: "[Toscana] Siena",
    order: 98,
    key: "toscana-siena",
    parent: 26,
  },
  {
    id: 699,
    value: "[Trentino Alto Adigio] Bolzano",
    order: 99,
    key: "trentino-alto-adigio-bolzano",
    parent: 26,
  },
  {
    id: 700,
    value: "[Trentino Alto Adigio] Trento",
    order: 100,
    key: "trentino-alto-adigio-trento",
    parent: 26,
  },
  {
    id: 701,
    value: "[Umbría] Perugia",
    order: 101,
    key: "umbria-perugia",
    parent: 26,
  },
  {
    id: 702,
    value: "[Umbría] Terni",
    order: 102,
    key: "umbria-terni",
    parent: 26,
  },
  {
    id: 703,
    value: "[Valle de Aosta] Aosta",
    order: 103,
    key: "valle-de-aosta-aosta",
    parent: 26,
  },
  {
    id: 704,
    value: "[Véneto] Belluno",
    order: 104,
    key: "veneto-belluno",
    parent: 26,
  },
  {
    id: 705,
    value: "[Véneto] Padua",
    order: 105,
    key: "veneto-padua",
    parent: 26,
  },
  {
    id: 706,
    value: "[Véneto] Rovigo",
    order: 106,
    key: "veneto-rovigo",
    parent: 26,
  },
  {
    id: 707,
    value: "[Véneto] Treviso",
    order: 107,
    key: "veneto-treviso",
    parent: 26,
  },
  {
    id: 708,
    value: "[Véneto] Venecia",
    order: 108,
    key: "veneto-venecia",
    parent: 26,
  },
  {
    id: 709,
    value: "[Véneto] Verona",
    order: 109,
    key: "veneto-verona",
    parent: 26,
  },
  {
    id: 710,
    value: "[Véneto] Vicenza",
    order: 110,
    key: "veneto-vicenza",
    parent: 26,
  },
  {
    id: 732,
    value: "Angola",
    order: 600,
    key: "angola",
    parent: 84,
  },
  {
    id: 733,
    value: "Resto de Africa",
    order: 600,
    key: "resto-de-africa",
    parent: 85,
  },
];

export const CONTRACT_TYPES = [
  {
    id: 0,
    value: "(Seleccionar)",
    order: 0,
    key: "seleccionar",
  },
  {
    id: 10,
    value: "Autónomo",
    order: 15,
    key: "autonomo",
  },
  {
    id: 8,
    value: "De duración determinada",
    order: 20,
    key: "de-duracion-determinada",
  },
  {
    id: 6,
    value: "De relevo",
    order: 30,
    key: "de-relevo",
  },
  {
    id: 9,
    value: "Fijo discontinuo",
    order: 40,
    key: "fijo-discontinuo",
  },
  {
    id: 3,
    value: "Formativo",
    order: 50,
    key: "formativo",
  },
  {
    id: 1,
    value: "Indefinido",
    order: 60,
    key: "indefinido",
  },
  {
    id: 4,
    value: "A tiempo parcial",
    order: 65,
    key: "a-tiempo-parcial",
  },
  {
    id: 5,
    value: "Otros contratos",
    order: 70,
    key: "otros-contratos",
  },
];

export const TELEWORKING = [
  {
    id: 0,
    value: "(Seleccionar)",
    order: 0,
    key: "indicar",
  },
  {
    id: 1,
    value: "Presencial",
    order: 1,
    key: "trabajo-solo-presencial",
  },
  {
    id: 2,
    value: "Solo teletrabajo",
    order: 2,
    key: "solo-teletrabajo",
  },
  {
    id: 3,
    value: "Híbrido",
    order: 3,
    key: "teletrabajo-posible",
  },
  {
    id: 4,
    value: "Sin especificar",
    order: 4,
    key: "no-se-sabe-no-esta-decidido",
  },
];
